Repository tkshill/Quarto, pull requests merged in 2020-10, with the labels that each got.

#9 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Type: Documentation

#12 Added favicon package
  public/favicon_package_v0/README.md
  public/favicon_package_v0/android-chrome-192x192.png
  public/favicon_package_v0/android-chrome-512x512.png
  public/favicon_package_v0/apple-touch-icon.png
  public/favicon_package_v0/browserconfig.xml
  public/favicon_package_v0/favicon-16x16.png
  public/favicon_package_v0/favicon-32x32.png
  public/favicon_package_v0/favicon.ico
  public/favicon_package_v0/html_code.html
  public/favicon_package_v0/mstile-150x150.png
  public/favicon_package_v0/safari-pinned-tab.svg
  public/favicon_package_v0/site.webmanifest
  public/index.html
Labels: Status: Accepted, hacktoberfest, hacktoberfest-accepted

#13 Docs: Updated readme
  README.md
Labels: Type: Documentation

#17 Template updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_template.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question_template.md
Labels: Type: Documentation

#18 Update Page titles
  .DS_Store
  src/Pages/NotFound.elm
  src/Pages/Quarto.elm
  src/Pages/Top.elm
Labels: hacktoberfest-accepted

#20 Refactor game state logic
  src/Pages/Quarto.elm
Labels: hacktoberfest-accepted

#24 Create Better Landing Page
  src/Pages/Top.elm
  src/Styles.elm
Labels: hacktoberfest, hacktoberfest-accepted

#29 Make buttons accessible
  src/Pages/GamePage.elm
Labels: hacktoberfest-accepted

#30 Effect pattern refactor
  src/Pages/GamePage.elm
  tests/ProgramTests.elm
Labels: Context: Refactor

#36 Added GitHub Repository link to footer
  src/Shared.elm
Labels: hacktoberfest-accepted

#33 Documentation Updates
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Assigned, Type: Documentation

#38 Update GH link to match site tone
  src/Shared.elm
Labels: hacktoberfest-accepted

#39 Add aria attributes
  src/Pages/GamePage.elm
  src/Shared.elm
Labels: Status: Accepted, hacktoberfest-accepted

#35 WIP Feature/add computer player
  src/Pages/GamePage.elm
Labels: Status: Needs Review, Type: Enhancement, hacktoberfest-accepted
